### ISSUE TITLE
[Suggestion] Adding JEI support

### ISSUE THREAD

**Issue by PlasmamsalP** [mraof/Minestuck#104]
Since you updated to 1.9.4, and there is no NEI support for that version, could you add JEI support to the mod instead? I think it would be better.

**Comment by kirderf1** [comment]
Yes, I was thinking of doing that, but forgot about it until now.

**Comment by PlasmamsalP** [comment]
Just a question, is there any kind of up-to-date list of alchematising recipes?

**Comment by kirderf1** [comment]
The only up-to-date list right now is the source code itself. If you care to try and read it, you should look in src/com/mraof/minestuck/util/AlchemyRecipeHandler.java.

**Comment by PlasmamsalP** [comment]
Oh thank you so much! I _was_ looking in the source code but I didnt really know where to look.
