### ISSUE TITLE
Pogohammer side-based bounce

### ISSUE THREAD

**Issue by kirderf1** [mraof/Minestuck#108]
The block side clicked on with the pogo hammer (and now pogo club) should affect the motion given. Right now the motion is strictly up, which allows the climbing of wallls simply by bouncing off them. The idea is to instead give just a slight upward movement (for horizontal sides) and a great movement away from the side clicked on.

**Comment by mraof** [comment]
Closed with https://github.com/mraof/Minestuck/commit/d7e04642de99d2cd5279534baaed4b3f73afc3d2

**Comment by kirderf1** [comment]
This is not fully finished, because it has yet to be done for the pogo club as well

**Comment by mraof** [comment]
I plan to do that for the pogo club at the same time as improving the weapon code, there's a lot of redundancy and the enums really aren't necessary
