### ISSUE TITLE
Question on Consort_Update

### ISSUE THREAD

**Issue by MrLaughingJack22** [mraof/Minestuck#119]
I'm a bit new to GitHub and how it works, but I'm in love with this mod and really want to ask: Do you may have a idea when the update to add consort interaction will be finished? And, what will become for the future?

**Comment by MrLaughingJack22** [comment]
Oh, and I may think this is too much but: If prototyping is ever going to be a thing, you totally should make a craftable and placeable Harlequin Doll to throw in.

**Comment by kirderf1** [comment]
Sorry, but we do not have a date that we aim the update towards yet

**Comment by BenjaminKirksey** [comment]
I do not have the authority to close this issue, but the point on harlequin dolls has been noted and the consort update is now live. I suggest this issue be closed.
