### ISSUE TITLE
Question about the posters

### ISSUE THREAD

**Issue by MarioBG** [mraof/Minestuck#120]
I was testing the mod in creative mode and saw the SBAHJ and Midnight Crew posters. Tried to place them on the wall, to no use. Maybe you could do as with vanilla paintings and make them placeable? I don't think it would take too much effort, especially since the source is already there. Dou you plan on implementing this? Thanks!

**Comment by kirderf1** [comment]
Midnight crew posters on their way. You'll have to wait a little longer for SBAHJ posters.
