### ISSUE TITLE
Allow Captchalouging of items in inventory by hovering over them and pressing the Captchalouge key

### ISSUE THREAD

**Issue by seriousCoolness** [mraof/Minestuck#123]

**Comment by Derpford** [comment]
Can we also get a dedicated keybind for either uncaptchalogueing the most recent item, or jumping directly to the Sylladex?

Similarly, once the Strife Specibus is implemented, having a dedicated key for cycling to the next item in the Strife Specibus would be a good idea.

**Comment by kirderf1** [comment]
I recall this being implemented.
