### ISSUE TITLE
Server Player Entity Eggs

### ISSUE THREAD

**Issue by hecksadecimal** [mraof/Minestuck#130]
If you activate edit mode as a server player and then middle click (block select) a mob, you will receive an egg for that mob if one exists. Minestuck attempts to remove this item from the hotbar, but there is a period of time between it appearing in the hotbar, and the item disappearing, wherein the egg is usable. By spam clicking the block select key and the right mouse button on a pre-existing mob, you can spawn in more entities.

**Comment by BenjaminKirksey** [comment]
And we need to either remove the period of time where spawning entities is possible, or we need to support using spawn eggs to make entities in Edit Mode. That question alone is a bit of a puzzle.

**Comment by kirderf1** [comment]
I don't think it's appropriate to have spawn eggs in editmode. Editmode is not only supposed to remove items without a grist cost or isn't a block/one of certain allowed items, but is also supposed to prevent any usage of these. I'd suggest looking into any issues with the latter.

**Comment by kirderf1** [comment]
This was fixed in commit https://github.com/mraof/Minestuck/commit/f51e050b27200b083e09f2abb6830583603ea8ad
