### ISSUE TITLE
Right click with Captchalogue Card containing item to put it back into the Sylladex

### ISSUE THREAD

**Issue by Derpford** [mraof/Minestuck#138]
Right now, you need to open a special GUI to put a captchalogue card back into the Sylladex. It might be easier for players to be able to right-click with a card containing an item to put it into the Sylladex. This could be especially useful if a keybind is added to retrieve an item from the Sylladex.

**Comment by kirderf1** [comment]
If the card has an item in it already, captchaloguing it normally should have that effect

**Comment by Derpford** [comment]
OK, that settles that.

**Comment by kirderf1** [comment]
I assume that this is not needed then
