### ISSUE TITLE
Game asks for color at every map start and resets collected grist

### ISSUE THREAD

**Issue by MaddoScientisto** [mraof/Minestuck#155]
Minecraft 1.12.2, only minestuck and minestuck arsenal installed
Log included
[minelog.txt](https://github.com/mraof/Minestuck/files/1544690/minelog.txt)

Every time I load a map I get asked for the color even if I chose it earlier and if I'm already in the medium then my grist supplies will all get reset to 0.
Seems to happen every time even on a fresh instance with only the mod

**Comment by kirderf1** [comment]
Should be fixed in build 225+.
Reopen if that's not the case.
