### ISSUE TITLE
Crash with Random Things

### ISSUE THREAD

**Issue by medsal15** [mraof/Minestuck#158]
Using Minestuck 1.12.2-1.2.232 and [Random Things](https://minecraft.curseforge.com/projects/random-things) 1.12.2-4.0.8

Crash log: https://pastebin.com/bfE2QHN8

The crash only happens when one of the [biome blocks](http://randomthingsminecraftmod.wikispaces.com/Biome+Blocks) tries to render in the inventory.

**Comment by mraof** [comment]
In what biomes does the crash happen?

**Comment by mraof** [comment]
https://github.com/lumien231/Random-Things/pull/260 This pull request to Random Things fixes the crash, based on my testing
