### ISSUE TITLE
Will Not Run Through Twitch

### ISSUE THREAD

**Issue by DragonMystic** [mraof/Minestuck#160]
I am trying to run this mod through the twitch launcher, and Minecraft comes back with this error: 
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minestuck (minestuck)

**Comment by kirderf1** [comment]
Looks like a cutoff from the crashlog
You think you can find the whole crashlog?

**Comment by DragonMystic** [comment]
I think I figured it out. It wouldn't run on minecraft 1.1, I did it on 1.12, seems to be working now. but that's all it was showing me when I pressed more info.
