### ISSUE TITLE
Can't edit mode while Applecore and/or Appleskin are installed.

### ISSUE THREAD

**Issue by Darkmega18** [mraof/Minestuck#169]
This is very weird. but myself and a friend were testing this mod together and when we got to using the computers etc we couldn't activate edit mode when connecting. at first we thought it cause of being cross dimension. so we moved to overworld, no go again. then moved it even closer, still no go. After that, friend got tired and left for sleep and I had to eat food.

when I came back I did science. I had made a very small mod list of not many mods. and so I cut it right back to minestuck and it worked in a singleplayer connecting to myself. so I slowly added more stuff in. first, graphical and interface mods. JEI, hwyla, minimap, applecore, apple skin, inventory tweaks and mousetweaks.

Tried it. stuck. nothing. "WTF, already?!" so... I took out the tweaks and applecore. it worked. at first I was like, "hmm. maybe the tweaks" and put those in. it worked. so I went back and put apple core and apple skin in. broke it.

so, this is really weird, and theres no crash or anything, it just stops editmode outright from working. :V Since skin won't work without core, it's probably the core. and without the applecore there goes a few good food related mods and a better food bar display. so, would you please be able to investigate this? I'm just going to keep adding the rest of the small amount of mods back in to see if there are any others doing it.

Edit: I've just tested it with a pack in progress of around 170 mods, and edit mode worked. although I did freeze when I hit the edge of the editzone too hard, but it could've been related to the lag I was already having. but most pressingly is the fact that applecore or appleskin seems to be stopping edit entirely, and hence practically most of the mod. :V

**Comment by Darkmega18** [comment]
yes. it gives a warning but it works absolutely fine. been upgrading my base heavily in the overworld using it and repurposed compressed cobblestone to make grist out of using refund mode in config.

**Comment by kirderf1** [comment]
Alright, nice
