### ISSUE TITLE
Ticking entity Crash, Apparently from a Basilisk of some kind.

### ISSUE THREAD

**Issue by Darkmega18** [mraof/Minestuck#171]
I didn't come across this crash for the 20-30 mins i spent fighting ogres, basilisks and lichs in the 800ish distance from my base after taking the portal that takes you way out. But then today after finding my friend had made transportals, I made and few and went to set up a sub-base deep into my land, but soon after it blew up and gave this crash report on the server.

[crash-2018-07-06_12.00.33-server.txt](https://github.com/mraof/Minestuck/files/2171162/crash-2018-07-06_12.00.33-server.txt)

Also as a side note, Skaia seems to be incredibly laggy tickwise (entities doing the slow walk, slightly rubber banding projectiles etc), probably due to maybe some sight range extensions and large amounts of mobs being everywhere? although we knew it was a work in progress area, friend wanted to go see it anyway. set up a portal location and room for it and everything. (during which time of explaining stuff to me he said they were pretty good renditions of the comic monsters. so, yay, thats a plus for you guys. :D)

**Comment by kirderf1** [comment]
Looks like a problem with minestuck arsenal. I recommend taking it to https://github.com/linkisheroic/minestuckarsenal/issues instead.

**Comment by Darkmega18** [comment]
Roger. I tried to find their hub but they don't have it linked with their curse page. I'll reference it over there now.
