### ISSUE TITLE
Edit mode tells me of "something happening", and throws this into the console when connecting to self via sburb

### ISSUE THREAD

**Issue by Darkmega18** [mraof/Minestuck#172]
After the using edit mode and disconnecting from myself after my testing it did do the thing where it says "client is already active" when it's not connected anymore. but there were no active sessions and nor did it stop me from reconnecting to myself after reopenning the sburb server. so not sure if visual or not. but heres the log from the multicraft console.

`14.07 12:55:05 [Multicraft] Skipped 12 lines due to rate limit (30/s) 14.07 12:54:47 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161] 14.07 12:54:47 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?] 14.07 12:54:47 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?] 14.07 12:54:47 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?] 14.07 12:54:47 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?] 14.07 12:54:47 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?] 14.07 12:54:47 [Server] INFO at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_161] 14.07 12:54:47 [Server] INFO at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_161] 14.07 12:54:47 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NullPointerException 14.07 12:54:47 [Server] Server thread/FATAL Error executing task 14.07 12:54:47 [Server] Server thread/ERROR [FML]: 1: ASM: com.natura.minestuckarsenal.EntityInteractEventHandler@4027720c onConnectionEnded(Lcom/mraof/minestuck/event/ConnectionClosedEvent;)V 14.07 12:54:47 [Server] Server thread/ERROR [FML]: 0: NORMAL 14.07 12:54:47 [Server] Server thread/ERROR [FML]: Index: 1 Listeners: 14.07 12:54:47 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161] 14.07 12:54:47 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?] 14.07 12:54:47 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?] 14.07 12:54:47 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?] 14.07 12:54:47 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?] 14.07 12:54:47 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?] 14.07 12:54:47 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161] 14.07 12:54:47 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161] 14.07 12:54:47 [Server] INFO at com.mraof.minestuck.network.MinestuckChannelHandler$MinestuckPacketHandler.lambda$channelRead0$1(MinestuckChannelHandler.java:68) ~[MinestuckChannelHandler$MinestuckPacketHandler.class:?] 14.07 12:54:47 [Server] INFO at com.mraof.minestuck.network.SburbConnectClosedPacket.execute(SburbConnectClosedPacket.java:49) ~[SburbConnectClosedPacket.class:?] 14.07 12:54:47 [Server] INFO at com.mraof.minestuck.network.skaianet.SkaianetHandler.closeConnection(SkaianetHandler.java:230) ~[SkaianetHandler.class:?] 14.07 12:54:47 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?] 14.07 12:54:47 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?] 14.07 12:54:47 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1667_EntityInteractEventHandler_onConnectionEnded_ConnectionClosedEvent.invoke(.dynamic) ~[?:?] 14.07 12:54:47 [Server] INFO at com.natura.minestuckarsenal.EntityInteractEventHandler.onConnectionEnded(EntityInteractEventHandler.java:84) ~[EntityInteractEventHandler.class:?] 14.07 12:54:47 [Server] INFO java.lang.NullPointerException: null 14.07 12:54:47 [Server] Server thread/ERROR [FML]: Exception caught during firing event com.mraof.minestuck.event.ConnectionClosedEvent@70d59cf5:`

upside down. cause multicraft does console bottom to top. :V I had connected twice. once to salvage a bunch of wood and use the grist to make a tower on my base to glide to a floating structure thingy in the sky. then once while on said structure to salvage vines and stuff off it and upgrade said structure for future use... :3

**Comment by kirderf1** [comment]
Looked at it now, and it appears that it crashes for arsenal,  so now I'll see if I can work this out with Rose.

**Comment by Darkmega18** [comment]
I see. ok thanks.

**Comment by linkisheroic** [comment]
It's partially fixed by 1.7.0. I think a change to the event is needed to get rid of it completely.
