### ISSUE TITLE
Crash when Flans mod is also installed.

### ISSUE THREAD

**Issue by singekoo** [mraof/Minestuck#195]
Should I post this bug to flans mod instead? I'm not sure.

This happens when I try and use flans mod with (mech, modern, simple, and titan packs.)

Forge: 14.23.5.2838

minestuck 1.12.2-1.4.287

https://paste.dimdev.org/madugovuzo.mccrash

**Comment by kirderf1** [comment]
Sorry for the late response. The problem here is that the dimension id for the skaia dimension conflicts with a different mod. To solve this, find the minestuck config file and change the skaia dimension id to different values until you find one that isn't used already.

**Comment by singekoo** [comment]
ohhh, I should have thought of that. sorry.
