### ISSUE TITLE
Crash while loading game

### ISSUE THREAD

**Issue by Katcie** [mraof/Minestuck#208]
[crash-2019-07-31_07.47.01-client.txt](https://github.com/mraof/Minestuck/files/3452455/crash-2019-07-31_07.47.01-client.txt)

Having an issue where the game will load, but crashes before the title screen appears. It worked fine when I first loaded it and played, but now it won't load up at all.

**Comment by kirderf1** [comment]
Can you tell me which keyboard key your captchalogue key is mapped to?

**Comment by Katcie** [comment]
Opening the captchalogue menu is ~/`, but the game originally crashed when I attempted to set a key for captchloguing an item and it must've stayed set to its default, which was either c or x.
