### ISSUE TITLE
Crash on loading help menu

### ISSUE THREAD

**Issue by Futurama39** [mraof/Minestuck#209]
reliably just using /help 5 in my case, there is a bugged command in that page (probably /landDebug) that causes the game to crash

![image](https://user-images.githubusercontent.com/12499845/62361554-93cde700-b51b-11e9-9a8a-7dd4906bca0f.png)

**Comment by kirderf1** [comment]
Weird. I'm not getting that error myself, so you'll have to send the crashlog and/or the list of mods with versions (including forge and minestuck version).

**Comment by Futurama39** [comment]
Okay so i was not able to reproduce on singleplayer, but on multiplayer i  can consistently reproduce it.

Mods running on client:
Baubles-Mod-1.12.2.jar
jei_1.12.2.-4.15.0.287.jar
Minestuck-1.12.2-1.4.292.jar
minestuckarsenal-1.12-1.8.0.jar
through forge 1.12.2-14.23.5.2838

Server:
DO server through gamocosm
Baubles-Mod-1.12.2.jar
jei_1.12.2-4.13.1.222
Minestuck-1.12.2-1.4.292.jar
minestuckarsenal-1.12-1.8.0.jar
through forge 1.12.2-14.23.4.2705


Now doing this on the clientside did not get a crash report since the game simply disconnected, but while running help 5 on serverside, it gave me more things [https://gist.github.com/Futurama39/91dec3857cfc5a23621eeed7df294452]here(url)

**Comment by kirderf1** [comment]
Alright, it seems to me that it doesn't crash if it tries to send it over "the network" first, or if it's sent directly to the server.
But anyways I know what's wrong and I'll go to fix it straight away now.
