### ISSUE TITLE
Trying to add compatibility

### ISSUE THREAD

**Issue by UnrefinedCatalyst** [mraof/Minestuck#225]
I have the lootbags mod, and it has the option to add items to the loodbag drop list

it has a section within its config that shows the loot tables from vanilla Minecraft that the mod draws from. 

for example:
        minecraft:chests/simple_dungeon
        minecraft:chests/abandoned_mineshaft
        minecraft:chests/desert_pyramid
        minecraft:chests/jungle_temple

if I knew what the loot tables for chests within the medium, or chests within the medium's dungeons are called, I would simply just have to copy and paste their tags into lootbag's config file.

I'd greatly appreciate it if someone would give me these tags.

**Comment by kirderf1** [comment]
The only chest type of loot as of right now goes by the name 
```
minestuck:chests/medium_basic
```
For reference, you can find all existing loot tables in 
[https://github.com/mraof/Minestuck/blob/1.12/src/com/mraof/minestuck/world/storage/loot/MinestuckLoot.java](https://github.com/mraof/Minestuck/blob/1.12/src/com/mraof/minestuck/world/storage/loot/MinestuckLoot.java)

Do note however that the consort loot tables use a consort predicate for most items, so a lot of those items will be unlikely to show up.
