### ISSUE TITLE
Combatability with other mods

### ISSUE THREAD

**Issue by UnrefinedCatalyst** [mraof/Minestuck#229]
Was just hoping you could list the mods that minestuck is integrated and compatible with, (With grist recipies and such) I was also hoping that you could add compatibility with Evilcraft.

**Comment by kirderf1** [comment]
In 1.12-, we have some degree of (more or less limited) integration with:
- Actually additions
- Extra utilities
- Refined storage (though no recipes or such)
- Tinkers construct
There's also stuff for Minegica 3 and Never say nether, but I am very uncertain whether the code for them has stayed in working condition for this long
None of the integration stuff has been updated to 1.14, so none of this is present in the current version
I have no plans on working on and adding any compabilities myself, but I'd be happy to accept any contributions that's well enough coded
