### ISSUE TITLE
Boondollars

### ISSUE THREAD

**Issue by UnrefinedCatalyst** [mraof/Minestuck#230]
I just thought it would be nice to be able to drop your boondollars from your Ceramic porkhollow into the item form so that you can give boondollars to other players. Or create some type way to transfer boondollars between players.

**Comment by kirderf1** [comment]
We don't have a fully refined feature for messing with the porkhollow, but we do have the porkhollow command which can both send boondollars to others and take out boondollars as items. Eventually, I hope to get something that's more integrated into the game, but this command is good enough for now.
