### ISSUE TITLE
[1.15.2][Mod Interaction] max health increases every time you die

### ISSUE THREAD

**Issue by Storm-Cloud** [mraof/Minestuck#263]
Forge 31.2.47
Minestuck 1.15.2-1.5.1.0
Cyclic 1.15.2-0.7.0

Actions: install Cyclic alongside Minestuck, climb the echeladder enough that you have some amount of extra HP, then die and respawn

Result: Max HP has increased by whatever amount extra you're supposed to have, at zombiechum this is 4hp or 2 hearts every death. dying again continues to further increase max HP by this amount, and the change is not effected by relogging or restarting minecraft.

Expected Behaviour: Max HP remains the same before and after death.

**Comment by kirderf1** [comment]
The fault is with cyclic's handling of max health modifiers in that version, so that's where changes has to happen to solve this.
