### ISSUE TITLE
being glitched in an endless void when entering medium

### ISSUE THREAD

**Issue by Mlatios** [mraof/Minestuck#264]
whenever I eneter the medium on any world I will always be glitched in a way to pretty much soflocks the game
![image_2021-01-14_185139](https://user-images.githubusercontent.com/77457655/104629242-89fd5c80-5699-11eb-90bd-28979df9cd32.png)

**Comment by kirderf1** [comment]
Could you give some more info on this? Does a stacktrace appear in the logs? Does this only occur in combination with some other mods? Does this mean you have a world save which you can share, that would have this issue?

**Comment by Mlatios** [comment]
I only have the base mod installed and it acts as if I went into a chunk error thing where I get glitched unable to move and the arm definetly shows that

**Comment by Mlatios** [comment]
Ill try redownloading the mod since it also seems to be causing these errors around the general overworld

**Comment by Mlatios** [comment]
nope even in older versions of the mod it still happens
