### ISSUE TITLE
Gates don't work for other people.

### ISSUE THREAD

**Issue by Dapperbot28** [mraof/Minestuck#277]
Today I attempted to enter my client player's gate to go to his client player. It did not work. The gate did nothing.

**Comment by Dweblenod** [comment]
Was their connection disrupted and are you sure that the person you helped enter has their own client player who has entered?

**Comment by kirderf1** [comment]
There are some natural ways for gates to not operate, such as when to destination gate exists, as dweb question was related to. I think what we need to do here is to have some way to convey to the player when this is the case for a player that's not teleporting.
The simplest solution is to just send a chat message to the player trying to go through the gate, but some other solution might be nicer.

**Comment by kirderf1** [comment]
Hmm, looks like there's a message for the destination gate being destroyed, and a message for destination land not yet existing, but only the first one is actually being used.
