### ISSUE TITLE
Some visual updates which will make Minestuck more cool

### ISSUE THREAD

**Issue by undyingUmbragee** [mraof/Minestuck#344]
I REALLY enjoy your mod, but here are some things, which i think about like they NEED to be added:
1. Underlings death effect. in original comic, when underlings die, they kinda explode with dark-yellow effects and their grist type splashes. and also they should drop grist immediately after they die.
2. Grist improvements. Grist canonically have their sound effects (they were heard in "[S] JOHN, SALVAGE YOUR WEAPON AND FIGHT ON!"), and they also supposed to flash slowly (same with Vitality Gel), grist needs to be discovered first to see how it looks in grist cache and alchemy menus, too. and when you collect grist, it should show how much grist did you collected ( i know that it does already, but it doesnt looks like in original comic, i want for everything to be very close to canon, as you can see)
3. Nameplates for underlings only, and Health Vial for all mobs in the game and players. i heard that this has been worked on  or planned already, but i am not sure about it, so i am posting this here.

**Comment by kirderf1** [comment]
Github issues are not appropriate for making batches of suggestions. I suggest that you post these in our discord server instead, or alternatively create multiple issues that focus on one suggestion each.

**Comment by undyingUmbragee** [comment]
alright
