### ISSUE TITLE
Lands not generating features when Terrablender is loaded

### ISSUE THREAD

**Issue by JediaKyrol** [mraof/Minestuck#399]
EDIT:  NEVERMIND, seems to be a conflict with Terrablender.  Chucked it and the mods dependent on it out and worldgen works again.  Transportalizer issue still exists, though, putting that in its own issue as requested.
----------------------------------------------------------------------------------------------------------------
Tried entering the Medium multiple times in Minestuck-1.18.2-1.8.1.1 and each has only generated terrain.  No Gates, dungeons, consort villages, etc.  Last one was "Land of Rabbits and Cold Forests"  Didn't even generate trees or spawn rabbits.  Just endless rolling hills of podzal.
I also noticed Transportalizers no longer allow access to travel between the base-game worlds and Minestuck Lands or Lands and Skaia.  Is this an intentional change (I checked the server config and the blacklist option is empty, so it should be allowing travel.)?

**Comment by kirderf1** [comment]
The transportalizer thing is not intentional. Please open a separate issue for it.

**Comment by Dweblenod** [comment]
It is good info that Minestuck may not play nice with Terrablender, thank you for sharing the Issue!
