### ISSUE TITLE
Alchemy cost problem

### ISSUE THREAD

**Issue by tiroalplato** [mraof/Minestuck#483]
I am playing on version 1.19.2, alchemy does not seem to be consuming the right amount of grist, one item costs the same as 999 of the same item, attached is a video showcasing this in action. 

https://github.com/mraof/Minestuck/assets/137072325/ee5b74f9-a776-44e5-a0c2-8be730fd4105

**Comment by kirderf1** [comment]
Fixed in 1.19.2-1.10.3.1 by 89e21068b72d5cd0e2caafe03fbcca19845012e4.
