### ISSUE TITLE
Lathe, punch designix and AND/OR

### ISSUE THREAD

**Issue by Mach12** [mraof/Minestuck#63]
Currently, the punch designix can do both || and && systems to assemble cards.
However, according to the Homestuck series itself, the || system is done by punching together 2 cards at once in the designix, and the && by inserting 2 cards at once in the lathe's card slot.

I suggest to restrict && to the lathe for coherence, but I'll understand if this suggestion is refused to siplify the gameplay (or to make the player need shale grist for both combinations).

**Comment by kirderf1** [comment]
Just so you know, I'm working on this right now on the 1.8 branch.
