### ISSUE TITLE
Imp size

### ISSUE THREAD

**Issue by kirderf1** [mraof/Minestuck#71]
I think the imps are too small, and belive they would look better if the height was increased to about one and a half block instead.

**Comment by BenjaminKirksey** [comment]
I have scaled imps up by 50% in a previous update. The issue has evolved to this: the current imp model doesn't look that great when scaled up (though I do agree that they still look _better_), and an entirely new model is suggested instead.

**Comment by kirderf1** [comment]
The size has been done. Adding a potentially new model is a different issue.
