### ISSUE TITLE
Crash with Iguanas

### ISSUE THREAD

**Issue by Sunconure11** [mraof/Minestuck#73]
I was trying out CrackedEgg's reptile mod, and its incompatible with your mod, because of the way your IDs are registered.

http://pastebin.com/nFN0tKmy

I suggest we start registering our mobs with a minestuck prefix, like we do with items.

**Comment by kirderf1** [comment]
I will probably add this to the 1.8 code before releasing it.

**Comment by Sunconure11** [comment]
Would it be possible to add it to 1.7.10? I think we could add it as a minor hotfix, since many modded players are probably not going to move to 1.8 for a bit of time.

**Comment by kirderf1** [comment]
Oh, didn't see that the build for that change failed..
