### ISSUE TITLE
Ummm... (1.7.10)

### ISSUE THREAD

**Issue by Sunconure11** [mraof/Minestuck#75]
For some reason, Minestuck broke on my server, and is crashing me when I enter my own server:

http://pastebin.com/34Nm6NAn

**Comment by Sunconure11** [comment]
It got fixed after creating a new world, but, I'll leave this open, in case it comes back.

**Comment by kirderf1** [comment]
I think I figured it out. It was a bug that makes Queuestack moduses crash the server. A fix will be up soon.
