### ISSUE TITLE
[Suggestion] Modtweaker support for 1.7.10 branch and later 1.8

### ISSUE THREAD

**Issue by Sunconure11** [mraof/Minestuck#83]
Since this mod probably won't be updated much on 1.7 due to the fact it is transitioning to 1.8, I figure one more update to 1.7 might be in order. Add support for Modtweaker, so one can add recipes to the various machines this mod adds without being a mod dev. It could also be coupled with something like Custom Items, so that one can create many things this mod probably won't add to 1.7. When Modtweaker is avaliable for 1.8, we can add support for that too.

**Comment by kirderf1** [comment]
Sounds like a good idea. I'll be working on it shortly.

**Comment by kirderf1** [comment]
Code is generally done, and am currently testing it. I have been doing some other stuff this week, so this didn't go as quick as it should otherwise.

**Comment by Sunconure11** [comment]
Is there any tutorial on how to use the inbuilt minetweaker support, or atleast, a way to get some example scripts? I know how to use minetweaker, but, I don't know how to use it with this mod.

**Comment by kirderf1** [comment]
It's kinda late now where I live, so I'll be doing it tomorrow.

**Comment by kirderf1** [comment]
https://github.com/mraof/Minestuck/wiki/MineTweaker3-support
