### ISSUE TITLE
[QUESTION] License regarding fluid rendering code for 1.8

### ISSUE THREAD

**Issue by AlexIIL** [mraof/Minestuck#86]
I would like to use your implementation of a fluid renderer (as I haven't found any elsewhere) but I can't see a license that might allow me to do so? I'm just wondering whether copy/pasting the code (with a few tweaks here and there) would be allowed?

**Comment by kirderf1** [comment]
It's open for copying and modifying, but I'd like some sort of credit put with the code so that others can see where the code originated from.
Should probably add something like that in the fluid model class myself.

**Comment by kirderf1** [comment]
Something like what I just did in @65b5c96339bde85fc899a157ceb844e77d8c865f.
Also, I didn't finish the rendering for gases but it shouldn't be too hard to do on your own as long as you know what you're doing. And it's only the model class that requires changes for that.

**Comment by AlexIIL** [comment]
Thanks. Fortunately I only need it for normal liquids so that won't be a problem.
