### ISSUE TITLE
Grist is too bouncy

### ISSUE THREAD

**Issue by S0llux** [mraof/Minestuck#88]
Just a suggestion but can you make it so grist wont drop 30 blocks away from the mob killed? :L 
seriously though grist likes to fly all over the place and it isnt affected by item magnets which is really annoying. at least make it drop within three blocks max of the mob killed or something? Just a suggestion sorry if it sounds rude/

**Comment by kirderf1** [comment]
I think I resolved this back when I only did these sort of stuff for the 1.8 version. I'll make sure to apply the same thing for the 1.7.10 version.

**Comment by kirderf1** [comment]
Yep. This was created at the 1.8 branch. (279774ce576f42740c6c0736240923ae15a14170)

**Comment by S0llux** [comment]
thank you then <3 also next time youre on the server pm me yer skype >->

**Comment by kirderf1** [comment]
I can be on the server right now.
