### ISSUE TITLE
Crash with the latest version of Forge 1.7

### ISSUE THREAD

**Issue by Sunconure11** [mraof/Minestuck#90]
http://pastebin.com/aJPU00Tj

It appears to be connected to entity IDs.

**Comment by kirderf1** [comment]
Ah, that issue have appeared in 1.8 too, but I never thought about doing something about it for 1.7.
In newer versions of forge, there's a limit on the entity id used for mapping, limiting it to 255 or lower. You can resolve it by changing the "entityIdStart" in the config. I recommend 201, as long as it doesn't collide with any other mods. (Which of course, is the reason why it's configurable)
I'll make sure to change the default value to avoid this issue being repeated.
